### ISSUE TITLE
Ghost Asterism Model Updates

### ISSUE THREAD

**Issue by swalker2m** [gemini-hlsw/ocs#1436]
After discussion with Steve, current understanding of the GHOST software requirements has diverged from the existing [`GhostAsterism` model](https://github.com/gemini-hlsw/ocs/blob/develop/bundle/edu.gemini.pot/src/main/scala/edu/gemini/spModel/gemini/ghost/GhostAsterism.scala).  A few adjustments need to be made to bring it in line with current needs:

* I believe `XBinning` and `YBinning` have been collapsed into `Binning` with values `1, 2, 4, 8`.
* I think the `DualTarget` asterism should be renamed `StandardRes` to pair with `HighRes` and to incorporate single target standard resolution mode.
* The `StandardRes` asterism should have `ifu2: Option[GhostTarget]` so that it can represent either single (if `None`) or dual target (if `Some`) modes and enforce the constraint that single-target mode uses IFU1.  This will require the base position calculation to take into account that there may not be an IFU2 star.
* `BeamSwitching` was perhaps overemphasized in the original design documents and I believe the current thinking is to achieve this capability in a different way.  Let's delete `BeamSwitching` altogether for now.

The default guide fiber state calculation may need adjustment after commissioning or may be removed altogether but I suggest that we leave it alone for now until this is better understood.

**Comment by sraaphorst** [comment]
All of this sounds quite straightforward and is largely what I recall from the discussion.

**Comment by swalker2m** [comment]
Additional updates:

1. `Binning` moves out of `GhostTarget` and into plain instrument config (but not needed for June)
2. It turns out that sky "targets" can be observed by either IFU.  These are not targets with proper motion, magnitudes, etc. per se but rather just coordinates.

For point 2, we need to update the model to reflect this possibility.  Perhaps `ifu1: Either[Coordinates, GhostTarget]` and `ifu2: Option[Either[Coordinates, GhostTarget]]`.  The problem is that opens up the possibility to allow both IFUs to observe a sky position which isn't really intended.  There are only a handful of possibilities.  Maybe an ADT:

```scala
sealed trait GhostStandardResTargets {
  def ifu1: Either[Coordinates, GhostTarget]
  def ifu2: Option[Either[Coordinates, GhostTarget]]
}

object GhostStandardResTargets {
  case class SingleTarget(target: GhostTarget) extends ...
  case class DualTarget(target1: GhostTarget, target2: GhostTarget) extends ...
  case class Ifu1TargetPlusSky(target: GhostTarget, sky: Coordinates) extends ...
  case class Ifu2TargetPlusSky(sky: Coordinates, target: GhostTarget) extends ...
}
```

**Comment by sraaphorst** [comment]
Since binning will be moved into plain instrument config, this task can be closed.
