### ISSUE TITLE
GHOST Instrument Component

### ISSUE THREAD

**Issue by swalker2m** [gemini-hlsw/ocs#1437]
My understanding is that we don't need much instrument configuration in the June release, but nevertheless we will at least want an instrument component.  It should have position angle and red and blue camera exposure times.  (Note, target setup is the focus of this release, and that information is included in the asterism and edited in the target component editor.)

The instrument is needed by AGS and for sequence generation so it needs to at least exist even if it is minimal.  Also, I think we'll want to have a way to identify which `Asterism` options are available to an observation and associating this with the instrument seems like the right thing to do.

**Comment by swalker2m** [comment]
I believe we can skip producing a GHOST instrument sequence iterator, at least for now.  We will want to provide here AGS strategy options (P2, and ?) and of course produce sequence data as all instruments do.

**Comment by cquiroz** [comment]
i think we need the iterator for the seqexec

**Comment by swalker2m** [comment]
> i think we need the iterator for the seqexec

You'll still get a sequence, it just won't have steps that vary GHOST configuration.  For example, you can set up an offset pattern or repeat loop and have 100 steps, but they will all have the same red and blue camera exposure times.

**Comment by cquiroz** [comment]
ok, that's probably enough

**Comment by sraaphorst** [comment]
I think I'm a bit confused about this: how do guide fibers and guide probes play together? I'm trying to wrap my head around what AGS will need to do for GHOST, and what options in the instrument configuration editor will determine what asterism observation modes are available.

**Comment by swalker2m** [comment]
Guide fibers and guide probes shouldn't play together, if I understand it.  We'll find a PWFS guide star just like we do for other instruments.

My idea was to put all the asterism configuration in the target component itself, so if that flies then nothing you set in the instrument configuration editor will impact the asterism.

**Comment by sraaphorst** [comment]
I guess I'm perhaps confused as to what the purpose of a guide fiber is, then.

Your idea makes sense from a UI perspective, absolutely, since that information determines the characteristics of the asterism. I guess I was thinking of the asterism configuration as an instrument mode, and thus thought it could be added to the instrument editor.

I'm still not crazy about the idea of the drawer-like configuration since I think that that will be confusing from a UI perspective, but given how densely packed the target configuration editor already is, I can't think of a better way off the top of my head except for perhaps a dialog that pops up, with a string summary of the configuration placed above the target table.

**Comment by swalker2m** [comment]
> I guess I'm perhaps confused as to what the purpose of a guide fiber is, then.

Me too, but I don't think this can be used for keeping the telescope tracking on the target. It is for "computing and applying centroiding corrections".  Steve can probably explain what that means.  If I'm right, you still need a traditional guide star.

**Comment by sraaphorst** [comment]
I'm just going to throw some very rough estimates as to these discussions as per @arturog8m's request this morning, and if you have any feedback, Shane, that would be great.

I'm thinking the instrument component and underlying model might take 3-5 days?

**Comment by SteveMargheim** [comment]
You'll need a Standard vs. High-Res mode selector in the instrument component since it changes which positioner(s) are available for targets

**Comment by sraaphorst** [comment]
Note that the UI work for 1438 and 1440 are now going to be included here. Given the dependencies between this and the target component, I will estimate this at 1 week.

**Comment by sraaphorst** [comment]
The basic instrument component is done. We will have to expand it as time goes, but I think for now we can mark this task as closed.
