### ISSUE TITLE
Asterism Configuration

### ISSUE THREAD

**Issue by swalker2m** [gemini-hlsw/ocs#1440]
The `SingleTarget` and `GhostStandardRes` asterisms have no additional configuration beyond the targets themselves but the `GhostHighRes` asterism does have a few settings.  It isn't clear which if any of these are needed for June.  Going by the `Asterism` model, it would include these values:

![asterismconfig](https://user-images.githubusercontent.com/4906023/37173937-d1407a0a-22f3-11e8-883c-0a07bb3106f2.jpg)

but maybe all we need for now is to be able to pick standard vs. high resolution?

**Comment by sraaphorst** [comment]
Ahhh... never mind: sorry, I was confused in my previous comment between the Asterism configuration and the Asterism target configurations.

Couldn't we include this information in the GHOST tab if we go that route?

Or what about including these in the GHOST editor? I know they are tied to the target environment editor, but it seems like they would seldom be changed once set. We could even just adjust the text at the top of the Target Environment table to indicate what the settings are. Indeed, perhaps there are already cases where we should be doing this? (GPI?)
![screen shot 2018-03-13 at 10 51 31 am](https://user-images.githubusercontent.com/8795653/37345851-90f1995e-26ac-11e8-82d7-d039dc2f0875.png)

**Comment by swalker2m** [comment]
> Couldn't we include this information in the GHOST tab if we go that route?

Keep in mind this is asterism configuration as a whole.  Each GHOST target has it's own bit of configuration, which I think is what you're referring to by the "GHOST tab".

> Or what about including these in the GHOST editor? 

The drawer is probably the easiest to implement option, if that's a concern.  Putting it in the instrument editor is also a possibility but ideally we should keep it with the target component since it changes several things about the UI there.

**Comment by sraaphorst** [comment]
Again, as UI work, and related to 1438, I'm guessing 2-3 days?

**Comment by sraaphorst** [comment]
This will be configured in the instrument editor as per our discussion this morning, so I'll include estimates in 1437.

**Comment by swalker2m** [comment]
I believe this task is not needed for June.  We will support the radio button selection between modes. Any additional configuration will be left to the future.

**Comment by sraaphorst** [comment]
As said, this has been partially implemented in the instrument component for resolution modes. Any further configuration is something we will have to rework into the UI n the future.
