### ISSUE TITLE
Asterism ConfigBuilder

### ISSUE THREAD

**Issue by swalker2m** [gemini-hlsw/ocs#1441]
To get the asterism configuration down to the seqexec, it will need to be included in the `IConfig` built up by the `TelescopeObsCompCB`.  It seems like a function `Asterism => List[ISysConfig]` to merge into the configuration is needed.  Parameter names TBD.

**Comment by sraaphorst** [comment]
Did you mean `TargetObsCompcCB`? I don't see a file named `TelescopeObsCompCB`.

As for this aspect of configuration building, I have not yet had to work with this, so I'm not sure how complicated this will be and what exactly will need to be done on both the OT and Seqexec ends.

**Comment by swalker2m** [comment]
> Did you mean TargetObsCompcCB?

Correct, that's the one.  This shouldn't be terribly difficult.  It just needs to read the `Asterism` and add new parameters to the `ISysConfig` which is just a weird `Map`.

**Comment by sraaphorst** [comment]
As stated, this should be easy. 1-2 days, I would imagine.

**Comment by swalker2m** [comment]
One additional wrinkle is that we're passing targets to the seqexec now for the first time.  In OCS2 code we don't apply proper motion corrections and instead pass the information on to the TCS.  It isn't clear whether this strategy will work for GHOST or if we'll need to apply proper motion correction first.

**Comment by sraaphorst** [comment]
This task is done, but we are going to have to - at some point - include proper motion correction.
