### ISSUE TITLE
Position Editor (TPE) for GHOST

### ISSUE THREAD

**Issue by swalker2m** [gemini-hlsw/ocs#1444]
Full TPE support for GHOST will involve drawing the IFUs along with their guide fibers, dedicated sky fibers, etc.  For June we want to minimize the TPE effort.  I believe the `TpeAsterismFeature` will already show and edit the two targets in standard resolution dual-target mode.

We need more details about the patrol field for the IFU positioner arms, but if it can be described by a simple shape we could plot it fairly easily.  Anything else?  This seems like a bonus for June.

**Comment by sraaphorst** [comment]
I just looked at the code for `TpeAsterismFeature`, and I believe that you are correct: this appears to iterate over all targets in an asterism and render them, and implements drag-and-drop for coordinates for any target in the asterism.

Thus, I agree that this can be left alone unless I have some extra time in which to draw the IFU position arms, provided they are not overly complex.

**Comment by swalker2m** [comment]
Also, I guess it shouldn't be too hard to show the base position / slew target if desired.

**Comment by sraaphorst** [comment]
True: since we're already getting the `Asterism`, we have the `basePosition` available, so it shouldn't take more than a little extra code to throw it in the TPE.

**Comment by sraaphorst** [comment]
This one should be fairly painless. Depending on what we decide to do, I think we will need no time at all to maybe one day.

**Comment by sraaphorst** [comment]
Apart from enforcing the GS separation, which is not really a TPE issue, this is done.
