### ISSUE TITLE
REL-4020: Maroon X Fixed Rotator

### ISSUE THREAD

**Issue by swalker2m** [gemini-hlsw/ocs#2022]
# Maroon X TCC Config
__(Or Why Type Safety is Paramount)__

There is a confusing issue surrounding [the update for Maroon X TCC config](https://github.com/gemini-hlsw/ocs/pull/1987). From what I gather, the fact that the `posAngle` parameter is being set to `fixed` is incorrect.  Here is the configuration we now send to the TCC for Maroon X observations:

```xml
<param name="posAngle" value="fixed"/>
<paramset name="fixed" type="rotator">
    <param name="ipa" value="0"/>
    <param name="cosys" value="Fixed"/>
</paramset>
```

From Javier:

> The definition of the of the predefined rotator configuration called “fixed” is as follow:

```xml
 <paramset name="fixed" type="rotator">
    <param name="ipa" value="0.0"/>
    <param name="cosys" value="Fixed"/>
 </paramset>
```

which matches.  I think the error is in adding the `posAngle` parameter.  Looking through the code, that is happening here:

https://github.com/gemini-hlsw/ocs/blob/develop/bundle/edu.gemini.wdba.xmlrpc.server/src/main/java/edu/gemini/wdba/tcc/TccFieldConfig.java#L63-L70

```java
// If the instrument adds something, create a rotator config and add it in
if (rotConfigName.contains(TccNames.FIXED)) {
    putParameter(TccNames.ROTATOR, rotConfigName);
    add(rc);
} else {
    putParameter(TccNames.POSANGLE, rotConfigName);
    add(rc);
}

```

At first blush it appears that in the case of a "fixed" rotator config name we shouldn't be adding a `posAngle` parameter at all and instead it should be

 ```xml
<param name="rotator" value="fixed">
```

followed by the same `fixed` rotator `paramset` above.  Unfortunately the case doesn't match though so it takes the `else` branch and adds `fixed` as the value of a `posAngle` parameter.

If this is correct, we just need to make the comparison case insensitive or change the name of the rotator config name to `Fixed` instead of `fixed` and test.  In summary,

```xml
<param name="rotator" value="fixed">
<paramset name="fixed" type="rotator">
    <param name="ipa" value="0"/>
    <param name="cosys" value="Fixed"/>
</paramset>
```

Note that the `posAngle` parameter would disappear altogether in this case.  Is this what is desired?

**Comment by andrewwstephens** [comment]
That sounds reasonable.  Does the predefined "fixed" config also include the rotator param ?
```xml
<param name="rotator" value="fixed">
```

It might also be worthwhile looking into observations with Altair and Cass Rotator = Fixed, which is what we are attempting to emulate.  From the OT:
```xml
       <paramset name="Altair Adaptive Optics" kind="dataObj">
          <param name="wavelength" value="BS_850_2500"/>
          <param name="adc" value="OFF"/>
          <param name="cassRotator" value="FIXED"/>
          <param name="ndFilter" value="OUT"/>
          <param name="mode" value="NGS"/>
        </paramset>
```
