### ISSUE TITLE
Target Model Fallout and Followup

### ISSUE THREAD

**Issue by tpolecat** [gemini-hlsw/ocs#853]
This issue is a staging area for remaining items and issues that may come up as a result of the target model switch. Nontrivial ones will become JIRA issues; it's just easier to see them all together at the moment.

Please add comments to this issue and I will gather issues up into this list.

**Scheduling Block**

- [x] Scheduling block editor in Observation UI.
- [x] Scheduling block construction on template instantiation.

**Phase 2 Warnings**

- [x] No scheduling block.
- [x] Scheduling block outside program semester.
- [x] No ephemeris elements for scheduling block.
- [x] No Horizons ID.

**Ephemeris**

- [x] Show current and scheduling block coordinates.
- [x] Show path in TPE.
- [x] Robot for TCS files.
- [x] Custom upload.

**TCS**

- [ ] Verify TCS target config.

**TOO**

- [ ] Verify HTTP TOO
- [x] Enable TOO in target editor

**Magnitude Editor**

- [x] Fix rendering of `_z` etc in labels.

**Pending Code Removal**

- [x] Old Horizons service
- [ ] Remainder of `skyobject`
- [x] Remainder of `target.system`
- [ ] Most of `SPTargetPIO`
- [ ] `MagnitudePIO`
- [ ] `ModelConverters`

**QV**

- [ ] Verify `NonSiderealCache`

**Comment by arturog8m** [comment]
Is this up-to-date?

**Comment by tpolecat** [comment]
Yep, I moved the remaining things to JIRA.
